### ISSUE TITLE
Error when downloading video

### ISSUE THREAD

**Issue by fullcounter** [jaw20/Crunchyroll-XML-Decoder#33]
I'm getting this message when I added the link (using choice 1) and after Booting up it show this message : 

```
Traceback (most recent call last):
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 425, in <module>
    makechoise()
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 358, in makechoise
    ultimate.ultimate(raw_input('Please enter Crunchyroll video URL:\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 303, in ultimate
    video_hls(filen, video_input, connection_n_)
  File "crunchy-xml-decoder\hls.py", line 270, in video_hls
    fetch_encryption_key(video)
  File "crunchy-xml-decoder\hls.py", line 255, in fetch_encryption_key
    video.keys[0].key_value = urllib2.urlopen(url = video.keys[0].uri).read()
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Press any key to continue . . .
```

Can't figure out what's wrong, I can download subtitle just fine

**Comment by alzamer2** [comment]
full i think you can close this too
