### ISSUE TITLE
Problem with crypto.

### ISSUE THREAD

**Issue by nigoki2** [jaw20/Crunchyroll-XML-Decoder#42]
Hello.
Today I had a bad surprise with this error message: 

python version=2.7.9 64 bit
OS Version=Windows 8 6.2.9200
System Type=AMD64
Crypto not installed
lxml installed
Cfscrape installed
Downloading link:http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win-amd64-py2.7.exe
100% [............................................................................] 996870 / 996870
Crypto Extracting.....
[*************************************************************************] %100Lxml Extracting.....
Traceback (most recent call last):
  File "D:\Crunchyroll-XML-Decoder-master\crunchy-xml-decoder.py", line 9, in <module>
    import functtest
  File "crunchy-xml-decoder\functtest.py", line 116, in <module>
    unzip_('.\\temp\\lxml.exe','.\\temp\\')
  File "crunchy-xml-decoder\functtest.py", line 13, in unzip_
    zf = zipfile.ZipFile(filename_)
  File "C:\Python27\lib\zipfile.py", line 778, in __init__
    self.fp = io.open(file, filemode)
IOError: [Errno 2] No such file or directory: '.\\temp\\lxml.exe'

All things worked fine so far.
Please couls you help me ?

**Comment by nigoki2** [comment]
Nevermind. Problem resolved after a reboot.
