### ISSUE TITLE
Bootup/downloading errors.

### ISSUE THREAD

**Issue by FacelessFresh** [jaw20/Crunchyroll-XML-Decoder#52]
It seems to do this on every video I am downloading now. A Few times it has Booted up now and gets through so much of the download process and then pops up with the following errors:

Booting up...

Traceback (most recent call last):
  File "C\CRDL\crunchy-xml-decoder.py", line 369, in <module>
    makechoise()
  File "C\CRDL\crunchy-xml-decoder.py", line 302, in makechoise
    ultimate.ultimate(raw_input('Please enter Crunchyroll video URL:\n'), '', ''
)
  File "crunchy-xml-decoder\ultimate.py", line 293, in ultimate
    video_hls(filen, video_input)
  File "crunchy-xml-decoder\hls.py", line 110, in video_hls
    video = find_best_video(uri)
  File "crunchy-xml-decoder\hls.py", line 100, in find_best_video
    playlist = m3u8.load(uri)
  File "C\CRDL\m3u8\__init__.py", line 43, in load
    return _load_from_uri(uri, timeout, headers)
  File "C\CRDL\m3u8\__init__.py", line 52, in _load_from_uri
    resource = urlopen(request, timeout=timeout)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Python27\lib\httplib.py", line 1121, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
Press any key to continue . . .

and then when running it by Run Queue command it does the following:

Booting up...

Traceback (most recent call last):
  File " C\CRDL\crunchy-xml-decoder.py", line 369, in <module>
    makechoise()
  File " C\CRDL\crunchy-xml-decoder.py", line 317, in makechoise
    queueu('.\\queue.txt')
  File " C\CRDL\crunchy-xml-decoder.py", line 106, in queueu
    ultimate.ultimate(line.rstrip('\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 293, in ultimate
    video_hls(filen, video_input)
  File "crunchy-xml-decoder\hls.py", line 110, in video_hls
    video = find_best_video(uri)
  File "crunchy-xml-decoder\hls.py", line 100, in find_best_video
    playlist = m3u8.load(uri)
  File " C\CRDL\m3u8\__init__.py", line 43, in load
    return _load_from_uri(uri, timeout, headers)
  File " C\CRDL\m3u8\__init__.py", line 52, in _load_from_uri
    resource = urlopen(request, timeout=timeout)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Python27\lib\httplib.py", line 1121, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
Press any key to continue . . .

As said that sometimes it will start downloading and get to around 12/143 or higher before it kicks in with the errors and seems to do it on every link I've tried in the half a week. I'm not sure if others are having this issue but figured I'd share in case others have a solution or so those that have more experience with figuring out how to fix these issues can take care of it.

**Comment by yuuuusha** [comment]
It seems like it's related to Crunchyroll. They may have been playing with their servers/website for a few days. I have been trying to download 1080p videos.

Try watching the video in your browser, I bet you will experience the same issue. If you use Chrome, open the Console tab of your developer tools by pressing F12 while playing the video. If the video doesn't start you will see an ERR_EMPTY_RESPONSE error code after a few seconds, the same error httplib is throwing.

But you're not alone. Other Redditors and crunchyroll subscribers are facing this problem too.

Actually I bypassed it by using youtube-dl.

**Comment by FacelessFresh** [comment]
if it's just on Crunchyrolls end that the issues are from then I'll just deal with it for now then. I have been using getFLV for now since it will get the job done but it can be a pain since it doesn't always work properly. Just being patient is the key I suppose.
