### ISSUE TITLE
Issue with installation of module

### ISSUE THREAD

**Issue by fixx1983** [jaw20/Crunchyroll-XML-Decoder#54]
Everything sims ok until this error appears:

Traceback (most recent call last):
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 9, in <module>
    import functtest
  File "crunchy-xml-decoder\functtest.py", line 116, in <module>
    unzip_('.\\temp\\lxml.exe','.\\temp\\')
  File "crunchy-xml-decoder\functtest.py", line 13, in unzip_
    zf = zipfile.ZipFile(filename_)
  File "C:\Python27\lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '.\\temp\\lxml.exe'

**Comment by insanedude63** [comment]
This is a Python error and not a crunchyroll-xml-decoder error.

My guess is you downloaded python 3 instead of python 2.7.15
