### ISSUE TITLE
Was downloading fine and then suddenly wasn't

### ISSUE THREAD

**Issue by kurogabae** [jaw20/Crunchyroll-XML-Decoder#61]
I just downloaded two videos and when I went to do a third I was given the following error. Nothing changed between the second download and my third attempt aside from time elapsed. 

----------

Booting up...

Traceback (most recent call last):
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 369, in <module>
    makechoise()
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 302, in makechoise
    ultimate.ultimate(raw_input('Please enter Crunchyroll video URL:\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 258, in ultimate
    vid_id = xmlconfig.find('media_id').string
AttributeError: 'NoneType' object has no attribute 'string'
Press any key to continue . . .

**Comment by reikitsune** [comment]
Same here, except with this error:
Traceback (most recent call last):
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 369, in <module>
    makechoise()
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 302, in makechoise
    ultimate.ultimate(raw_input('Please enter Crunchyroll video URL:\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 258, in ultimate
    vid_id = xmlconfig.find('media_id').string
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by reikitsune** [comment]
> 
> 
> Same here, except with this error:
> Traceback (most recent call last):
> File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 369, in
> makechoise()
> File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 302, in makechoise
> ultimate.ultimate(raw_input('Please enter Crunchyroll video URL:\n'), '', '')
> File "crunchy-xml-decoder\ultimate.py", line 258, in ultimate
> vid_id = xmlconfig.find('media_id').string
> AttributeError: 'NoneType' object has no attribute 'string'

I have discovered that this error occurs after a single episode is downloaded. Then the error starts up. The program works after waiting like 15-30mins. But the site works completely fine while the error is occurring.

**Comment by AhmadKahlid** [comment]
The problem because cloudflare check, just replace the following file to fix it.
[altfuncs.zip](https://github.com/jaw20/Crunchyroll-XML-Decoder/files/2921427/altfuncs.zip)

**Comment by darkhelmet2016** [comment]
> The problem because cloudflare check, just replace the following file to fix it.
> [altfuncs.zip](https://github.com/jaw20/Crunchyroll-XML-Decoder/files/2921427/altfuncs.zip)

Will they let you put the fix in the main file or do only certain users have access to those files?

**Comment by darkhelmet2016** [comment]
These files need a serious update. https://github.com/jaw20/Crunchyroll-XML-Decoder/tree/master/crunchy-xml-decoder
